version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: syzyf
      POSTGRES_PASSWORD: mamdosc
    ports:
      - "5432:5432"  # Przekierowuje port 5432 z hosta na port 5432 w kontenerze
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"  # Przekierowuje port 8888 z hosta na port 80 w kontenerze
    depends_on:
      - db

volumes:
  postgres-data:  # Tworzy wolumen dla danych PostgreSQL, aby dane pozostały zachowane między uruchomieniami kontenera
