version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8888:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

